### PR TITLE
Addition of the possibility to avoid filtering of channels when expor…

### PR DESCRIPTION
**Pull request by Gijom**
Adding the possibility to unselect channels to filter when converting from BDF to EDF
- each channel filter can be unselected;
- it results that this channel is not filtered and the filter cutoff it indicated as 0Hz in the EDF file.

**Reason for the change:** I have BDF files from Biosemi Active II including a "status" channel. This channel should not be filtered since it contains triggers and other binary information which would be corrupted by the filter.

**Main code changes:**
- Addition of filter select boxes in the convert window (more precisely in `SignalsTablewidget`);
- Extension of the window size to fit the new boxes, and adjustement of buttons, etc;
- `filterlist` is set to NULL if the signal is not filtered, signals are filtered by default;
- later if `filterlist` is NULL than no filter is applied and 0Hz is written in `scratchpad`.

**Advantages:**
- more flexibility for special signals (e.g. status channel but also other "homemade" sensors plugged in the front box of the Biosemi);
- previously the result of the `createfilter` function was never tested althought it could return NULL in case of memory allocation problems This implementation solves potential crashes since in this case the signal would simply not be filtered.

**Disavantage:** in the case the `createfilter` function returns NULL there would be no error/warning and the unfiltered signal output would go against user expectations. Note that this could be solved easily, it was just not the goal of this modification.

I hope this could be of interest to you. Thanks for keeping me aware.

### CODE REVIEW

**Comment by Teuniz** [comment]
There is already a solution for this problem. Use the Biosemi to BDF+ converter:

http://www.teuniz.net/edfbrowser/EDFbrowser%20manual.html#Biosemi_to_BDFplus

Then you can use the BDF to EDF converter and the annotations will be okay.

I don't want to "create" a new EDF format that contains a non-standard status channel that can not be read by most programs.
Imho, using the Biosemi to BDF+ converter is a more elegant solution because we should standardize to a (defacto) standard instead of using different implementations from different manufacturers.

**Comment by Gijom** [comment]
Ok with me, I agree with the will to push manufacturers toward defacto standards, and will give a try to your solution.

I keep the fork open in the case someone want to use this implementation which can be faster in some cases (no need for double conversion). I will try to keep merges active. Note that both EDFReader and my other "output" program, Captiv, could read the output file.

**Comment by Gijom** [comment]
Sorry, just to continue the discussion and improve my knowledge of EDF. Is it an EDF standard to force filtering of signals ? Because I can imagine plenty of cases where signal filtering should be avoided (apart from the Biosemi status channel). Hence the patch could still be useful.

Example include already filtered signals which I do not want to filter again.

**Comment by Teuniz** [comment]
In order to remove 8 bits from the 24-bits samples to make them fit into the 16-bit samples, one has to decide which bits to remove. There are different solutions depending on the application.
For example, one can remove the 8 most significant bits, which effectively clips the signal.
Or remove the 8 least significant bits, which effectively removes the details and make the signal look coarse.
Combinations of both are possible, e.g. remove the 4 most significant bits and the 4 least significant bits.

In EDFbrowser, the 8 most significant bits will be removed when converting from BDF to EDF.
This can be done because, apart from DC, the signals of interest are usually well within this range.
However, in biomedical applications, 24-bit adc's usually have a DC connection with the electrodes.
The electrode-skin connection causes a high DC-offset. The analog input frontend has also a DC-offset. This causes clipping when removing the 8 most-significant bits. In order to remove this DC-offset, we need to apply a highpass-filter.

**Comment by Teuniz** [comment]
"Example include already filtered signals which I do not want to filter again."

Genuine Biosemi recordings in BDF format are not highpass filtered.
The highpass filters selected in the Biosemi application affects only the displayed data. Not the data in the recorded file.

**Comment by Gijom** [comment]
Clipping: crystal clear thanks for the explanation.
Filter: I know that Biosemi does not filter signals. But I sometimes use BDF as an intermediary data transfer solution. For instance after segmentation and filtering.

Pull request closed.

**Pull request closed without merging**
