### PR TITLE
Upgraded Power Spectrum

### PR DESCRIPTION
**Pull request by andrasfuchs**
Changes
-----------

There are many changes in this pull request in the following areas:

* Software architecture
  * Added .gitattributes to standardize line endings in files, and .gitignore to avoid personalized config file/temp file/generated file conflicts.
  * Added multi-target support, so the source can be compiled with Visual Studio 2013 Community Edition and the Visual C compiler.
  * The compilation with QtCreator is not effected.
  * All the target-specific definition are now in the multitargersupport.h file.
  * Moving towards to OOP design
  * Moving towards the Model-View-Controller design pattern's source code separation

* new Power Spectrum
  * new looks
  * support for different mouse gestures (dragging (click+move), zoom (mousewheel), reset zoom (double-click))
  * multi-signal support on one histogram (but it's still backward compatible)
  * color bar text positioning
  * support for "blind spots" for unavailable data
  * values are formatted with a thousand separator char
  * cursor displays the unit as well
  * new controls to change the Y-axis, turn the colorbars on/off and for signal selection
  * calculation of the input signal's on 3 different time-intervals
  * performance improvements

* real-time playback (Ctrl+Space)

Screenshots
----------------

Power Spectrum with multiple signals

Power Spectrum with multiple signals zoom

Power Spectrum controls

One signal and the controls

One signal, the color bars and the controls

### CODE REVIEW

**Comment by Teuniz** [comment]
Thank you for your interest but, for various reasons, this project does not and will not support microsoft tools.
Consider to use Linux for modifying, developing and testing of EDFbrowser.

**Comment by andrasfuchs** [comment]
Thank you for the quick reply!

None of the changes I made will effect the compilation on Linux. I understand that you don't want to use Microsoft tools, I don't use them either, I decided to compile EDFBrowser with QtCreator and minGW. 

Debugging in QtCreator, the git files are small improvements, but the main reason you should consider accepting my pull request is the upgraded power spectrum.

Now users can move around, zoom in and out using the mouse only, in an intuitive way.

If you don't accept the modifications, that's fine, I will continue to work on my fork, and I will implement a few more features I will use.

You can also decide later, I will leave the pull request here and update its description just in case you change your mind.

I think it would be beneficial for both of us, and for the users to keep one codebase most up-to-date and feature rich, though ;)

**Comment by Teuniz** [comment]
It doesn't compile. See the below output:

g++ -c -pipe -Wextra -Wshadow -Wformat-nonliteral -Wformat-security -Wtype-limits -Wfatal-errors -O2 -Wall -W -D_REENTRANT -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I/usr/local/Trolltech/Qt-4.8.7/mkspecs/linux-g++ -I. -I/usr/local/Trolltech/Qt-4.8.7/include/QtCore -I/usr/local/Trolltech/Qt-4.8.7/include/QtNetwork -I/usr/local/Trolltech/Qt-4.8.7/include/QtGui -I/usr/local/Trolltech/Qt-4.8.7/include -I. -Imoc -o objects/signalcurve.o signalcurve.cpp
signalcurve.cpp: In member function ‘virtual void SignalCurve::wheelEvent(QWheelEvent*)’:
signalcurve.cpp:386:49: warning: declaration of ‘event’ shadows a member of 'this' [-Wshadow]
 void SignalCurve::wheelEvent(QWheelEvent * event)
                                                 ^
signalcurve.cpp:391:27: error: ‘class QWheelEvent’ has no member named ‘angleDelta’
     QPoint delta = event->angleDelta();
                           ^
compilation terminated due to -Wfatal-errors.
Makefile.Release:5738: recipe for target 'objects/signalcurve.o' failed

**Comment by andrasfuchs** [comment]
The reason must be that I used the mouse-wheel related property angleDelta of the QWheelEvent class which is only available in Qt 5.5, and you tried to use Qt 4.8. 

See the difference here:
Qt 4.8: http://doc.qt.io/qt-4.8/qwheelevent.html
Qt 5.5: http://doc.qt.io/qt-5/qwheelevent.html

**Comment by Teuniz** [comment]
Qt5 is not (yet) ready for production use. It's full of bugs, some of them are reported long time ago and still not fixed. Unfortunately, the developers of Qt now focus mainly on mobile targets, unless you pay them.
For example, it's still impossible to compile the Qt5 libraries with the options "-static" and "-no-opengl" which is necessary for distribution on windows where it's important to have all libraries linked into the executable instead of dealing with separate dll's that ultimately creates an unmanageable mess.
So, EDFbrowser must be able to compile with Qt4.

**Comment by andrasfuchs** [comment]
Alright, thank you for the info, I didn't know that! 
I'll try to do the mouse-zooming with Qt 4.8 then, and let you know as soon as it works!

**Comment by Teuniz** [comment]
In biox2edf.cpp:

392 -   wr_buf[j] += (tmp_bits >> 6) & 0b00000011;
377 +   wr_buf[j] += (tmp_bits >> 6) & 0x0b00000011;

No offence but do you have any clue about what you just did there?

https://gcc.gnu.org/onlinedocs/gcc-4.8.3/gcc/Binary-constants.html

**Comment by andrasfuchs** [comment]
Jeez, sorry, that looks like a pretty bad mistake!

**Comment by Teuniz** [comment]
In check_edf_file.cpp:

1631        -#ifdef Q_OS_WIN32
1632        -      __mingw_sprintf(txt_string, "Error, filesize does not match with the calculated filesize based on the parameters\n"
1633        -                          "in the header. Filesize is %lli and filesize according to header is %lli.\n"
1634        -                          "You can fix this problem with the header editor, check the manual for details.",
1635        -                          l_tmp2, l_tmp);
1636        -#else
1637  1611      sprintf(txt_string, "Error, filesize does not match with the calculated filesize based on the parameters\n"
1638  1612                          "in the header. Filesize is %lli and filesize according to header is %lli.\n"
1639  1613                          "You can fix this problem with the header editor, check the manual for details.",
1640  1614                          l_tmp2, l_tmp);
1641        -#endif


http://sourceforge.net/p/mingw-w64/wiki2/gnu%20printf/

The EDFbrowser executable for windows is still compiled and tested on windows XP.

**Comment by andrasfuchs** [comment]
That logic was moved to multitargetsupport.h:
>#if defined(Q_OS_WIN32) && !defined(_MSC_VER)
>
>#define snprintf __mingw_snprintf
>#define sprintf __mingw_sprintf
>#define fprintf __mingw_fprintf
>
>#endif

Is this not good this way?

**Comment by Teuniz** [comment]
I overlooked that. It should be ok.

**Comment by andrasfuchs** [comment]
Hi Teuniz!

I've made many changes in the last few weeks to your project. I hope you will see them as improvements and you will include this pull request in the future releases, but I totally understand if you decide not to, since it affects important parts of your project.

If you could spare some time to check it out and let me know what you think, that would be great!

Thank you!

**Comment by Teuniz** [comment]
Hi Andras,

Have you tried to compile it on Linux?
I guess you didn't because your fork doesn't compile here...

Best,

Teuniz

**Comment by andrasfuchs** [comment]
Damn, that's not good.

I know that you are not a big fan of Windows :), and I was very careful not to use any platform specific code. It compiles here with Qt 4.8.6 and MinGW 4.9.2 though.

Do you have any tips for me how to fix it? What error message did you get?

Unfortunately I have no Linux development environment here...

**Comment by Teuniz** [comment]
>> I know that you are not a big fan of Windows :)

In that case, don't offend me by asking me to pull in code that hasn't been tested on Linux :)

>> Unfortunately I have no Linux development environment here...

That's easy to fix: http://www.linuxmint.com/edition.php?id=204

I guess you didn't use valgrind. So, please tell me, how did you check for memory leaks and illegal memory access?

**Comment by andrasfuchs** [comment]
Sure, I understand that Linux is the absolute priority for you.

Thanks for the link, I will check the that out!

Valgrind is [not available on Windows](https://forum.qt.io/topic/15169/how-can-we-use-valgrind-tools-of-qt-creator-to-check-memory-leaks-in-windows-and-mac-63), and although I looked for hours for a good solution on Windows, I could not find anything satisfactory and free.

I'll get back to you, when I can compile it on Linux.

Thanks

**Comment by Teuniz** [comment]
"terminate called after throwing an instance of 'std::runtime_error'
  what():  multiplier overflow in calculateRulerParameters
Aborted"

**Comment by Teuniz** [comment]
For various reasons I have decided not to pull in your patches.

- Your patch is too big. Your modifications to the signalcurve class have a programwide impact.

- Unnecessary usage of C++ language in places where plain C could have been used.

- The impact on stability is a concern for me. I don't have the impression that you test all kind
  of usecases very carefully with lots of different test files.

- Obviously, we have different preferences. I prefer to do all development on Linux,
  you prefer to do it on windows.
  You prefer to use C++, I prefer C.
  In my opinion, C++ is a horrible language. I just use the bare minimum in order to use Qt.
  You prefer to use microsoft tools, I don't.
  I always try to encourage people to move away from windows, I guess you don't.
 
After having said this, I do think that what you tried to achieve has merit. Maybe in the future
when I have more time, I'll try to replicate some parts of your ideas.

For the moment, I believe it's better if we keep our codebases separated.

**Comment by Teuniz** [comment]
The file playback function has been implemented.

**Comment by andrasfuchs** [comment]
Despite the fact that I would love to see my improvements in the next release of EDFBrowser, I have to say that I totally agree with your points.

I will continue to implement some new features I will need on my fork, and will keep an eye on yours.

Keep up the good work, and feel free to use any of my code if you think it's usable in yours!

**Pull request closed without merging**
